version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-20}
    container_name: grape-shop-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_VERSION=${NODE_VERSION:-20}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - STORAGE_PUBLIC_BASE_URL=${STORAGE_PUBLIC_BASE_URL}
      - MAIL_TRANSPORT=${MAIL_TRANSPORT}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - YOUKASSA_SHOP_ID=${YOUKASSA_SHOP_ID}
      - YOUKASSA_SECRET_KEY=${YOUKASSA_SECRET_KEY}
      - YOUKASSA_RETURN_URL=${YOUKASSA_RETURN_URL}
    volumes:
      - ./logs:/app/logs
    networks:
      - grape-network
    # Database is running separately, so we don't need to depend on it here

networks:
  grape-network:
    driver: bridge
